/*
|--------------------------------------------------------------------------
| DATA > CRAFTING
|--------------------------------------------------------------------------
*/
var items = [
	{
		id: "acid",
		name: "Acid",
		type: "Crafted Products",
		description: "Dilute acid for high current generation in diverse power cells.",
		value: 188000,
		ingredients: [
			{
				id: "mordite",
				name: "Mordite",
				quantity: 25
			}, 
			{
				id: "fungal_mould",
				name: "Fungal Mould",
				quantity: 600
			}
		]
	},
	{
		id: "activated_cadmium",
		name: "Activated Cadmium",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. This Cadmium has been activated by the extreme conditions in which it was formed, and is highly valuable. Cadmium is found on planets orbiting red stars, and can be placed in a Refiner to create purified Chromatic Metal.",
		value: 450
	},
	{
		id: "activated_copper",
		name: "Activated Copper",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. This Copper has been activated by the extreme conditions in which it was formed, and is highly valuable. Copper is found on planets orbiting yellow stars, and can be placed in a Refiner to create purified Chromatic Metal.",
		value: 245
	},
	{
		id: "activated_emeril",
		name: "Activated Emeril",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. This Emeril has been activated by the extreme conditions in which it was formed, and is highly valuable. Emeril is found on planets orbiting green stars, and can be placed in a Refiner to create purified Chromatic Metal.",
		value: 696
	},
	{
		id: "activated_indium",
		name: "Activated Indium",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. Indium is found on planets orbiting blue stars, and can be placed in a Refiner to create purified Chromatic Metal. This Indium has been activated by the extreme conditions in which it was formed, and is highly valuable.",
		value: 949
	},
	{
		id: "aronium",
		name: "Aronium",
		type: "Raw Materials",
		description: "A lightweight and highly malleable alloy. Crafted from Paraffinium and Chlorine. In high demand on the Galactic Trade Network due to its utility in the construction of planetside outposts and facilities.",
		value: 25000,
		ingredients: [
			{
				id: "paraffinium",
				name: "Paraffinium",
				quantity: 50
			}, 
			{
				id: "ionised_cobalt",
				name: "Ionised Cobalt",
				quantity: 50
			}
		]
	},
	{
		id: "basalt",
		name: "Basalt",
		type: "Raw Materials",
		description: "Local mineral extract, typically found in large deposits or extracted from common minerals after inspection with an Analysis Visor. Typically found on planets with a volcanic environment.",
		value: 62
	},
	{
		id: "cactus_flesh",
		name: "Cactus Flesh",
		type: "Raw Materials",
		description: "Succulent, edible cactus flesh from the Echinocactus plant. As well as being juicy on the tongue, the flesh has many industrial uses. The Echinocactus thrives only on desert planets, but can be farmed in all environments with the aid of a Hydroponics Tray.",
		value: 28
	},
	{
		id: "cadmium",
		name: "Cadmium",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. Such stellar material ends up forming deposits in the crust of local planets. Cadmium is found on planets orbiting red stars, and can be placed in a Refiner to create purified Chromatic Metal for use in the manufacture of advanced technologies.",
		value: 234
	},
	{
		id: "carbon",
		name: "Carbon",
		type: "Raw Materials",
		description: "The building block of all organic life. Of critical importance to space travelers, as Carbon is used to recharge mining equipment. The Mining Laser will harvest Carbon from trees, plants, and all other forms of vegetation.",
		value: 12
	},
	{
		id: "chlorine",
		name: "Chlorine",
		type: "Raw Materials",
		description: "A reactive element most easily harvested by processing the salt-infused minerals found in oceans. Used in the manufacture of advanced technologies.",
		value: 602
	},	
	{
		id: "chromatic_metal", 
		name: "Chromatic Metal",
		type: "Raw Materials",
		description: "A processed metal alloy, created in a Refiner from the stellar metals: Copper, Cadmium, Emeril and Indium. The rarer the stellar metal, the more Chromatic Metal it will produce. This valuable metal is used in the creation of many advanced technologies.",
		value: 245
	},
	{
		id: "circuit_board",
		name: "Circuit Board",
		type: "Crafted Products",
		description: "Stackable, semi-flexible circuit board made from a highly durable synthetic polymer.",
		value: 916250,
		ingredients: [
			{
				id: "poly_fibre",
				name: "Poly Fibre",
				quantity: 1
			},
			{
				id: "heat_capacitor",
				name: "Heat Capacitor",
				quantity: 1
			}
		]
	},	
	{
		id: "cobalt", 
		name: "Cobalt",
		type: "Raw Materials",
		description: "Mined from underground minerals, cobalt is found in plentiful supply in caves and caverns. Useful in the manufacture of Ion Batteries. It is used in the creation of several technologies and structures, and can be processed in a Refiner to make the most of its inherent charge.",
		value: 198
	},
	{
		id: "condensed_carbon", 
		name: "Condensed Carbon",
		type: "Raw Materials",
		description: "Advanced material, processed from regular carbon in a Refiner. The increased molecule density offers a substantially improved energy-per-gram ratio. Occasionally found in crystalline form. Harvesting large crystals may require an Advanced Mining Laser.",
		value: 24,
		ingredients: [
			{
				id: "carbon",
				name: "Carbon",
				quantity: 2
			}
		]
	},
	{
		id: "copper",
		name: "Copper",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. Such stellar material ends up forming deposits in the crust of local planets. Copper is found on planets orbiting yellow stars, and can be placed in a Refiner to create purified Chromatic Metal for use in the manufacture of advanced technologies.",
		value: 121
	},
	{
		id: "cryo_pump",
		name: "Cryo-Pump",
		type: "Crafted Products",
		description: "An advanced, self-regulating hybrid material, the Cryo-Pump distributes heat across itself with near perfect efficiency, making it vital in the creation of thermal regulators.",
		value: 1500000,
		ingredients: [
			{
				id: "hot_ice",
				name: "Hot Ice",
				quantity: 1
			}, 
			{
				id: "thermic_condensate",
				name: "Thermic Condensate",
				quantity: 1
			}
		]
	},
	{
		id: "cryogenic_chamber",
		name: "Cryogenic Chamber",
		type: "Crafted Products",
		description: "A low temperature chamber, designed to prevent the natural decay of organic matter.",
		value: 3800000,
		ingredients: [
			{
				id: "living_glass",
				name: "Living Glass",
				quantity: 1
			}, 
			{
				id: "cryo_pump",
				name: "Cryo-Pump",
				quantity: 1
			}
		]
	},
	// {
	// 	id: "cursed_dust",
	// 	name: "Cursed Dust",
	// 	type: "Raw Materials",
	// 	description: "A powdery desert soil, slick with the gland expressions of a colossal sandworm. Historically, some have regarded this dust the divine parent of such worms. It smells curiously sweet. Cursed Dust gathers in the terrain of planets blighted by titan worm activity.",
	// 	value: 959
	// },
	{
		id: "cyto_phosphate",
		name: "Cyto-Phosphate",
		type: "Raw Materials",
		description: "A blue-green organic compound produced during the metabolic cycle of deep-sea plantlife. Rich in soluble energy, cyto-phosphates are crucial in many submarine technologies. The Mining Laser will harvest cyto-phosphate compounds from underwater flora.",
		value: 201
	},
	{
		id: "deuterium",
		name: "Deuterium",
		type: "Raw Materials",
		description: "A stable hydrogen isotope used heavily in both small-scale fusion reactors and neutron-scattering shield technology. Deuterium very rarely occurs naturally. Most of the galaxy's supply comes from the processing of Di-hydrogen and Tritium in Refiners.",
		value: 34
	},
	{
		id: "di_hydrogen",
		name: "Di-hydrogen",
		type: "Raw Materials",
		description: "A stable, crystalline form of hydrogen remarkable both for its extreme energy density and its stability at atmospheric pressures. Common to all worlds, Di-hydrogen is found in the form of large blue crystals. It is a key component of Starship Launch Fuel.",
		value: 34
	},
	{
		id: "dioxite",
		name: "Dioxite",
		type: "Raw Materials",
		description: "Local mineral extract, typically found in large deposits or extracted from common minerals after inspection with an Analysis Visor. Typically found on planets with a frozen environment.",
		value: 62
	},
	{
		id: "dirty_bronze",
		name: "Dirty Bronze",
		type: "Crafted Products",
		description: "A popular metal alloy with a wide variety of uses. 'Dirty Bronze' has shed its scientific name in favor of the popular term for its colour.",
		value: 25000,
		ingredients: [
			{
				id: "pyrite",
				name: "Pyrite",
				quantity: 50
			}, 
			{
				id: "pure_ferrite",
				name: "Pure Ferrite",
				quantity: 100
			}
		]
	},
	{
		id: "emeril",
		name: "Emeril",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. Emeril is found on planets orbiting green stars, and can be placed in a Refiner to create purified Chromatic Metal for use in the manufacture of advanced technologies.",
		value: 348
	},
	{
		id: "enriched_carbon",
		name: "Enriched Carbon",
		type: "Crafted Products",
		description: "A refined product, taking ordinary carbon and boosting it with radioactive energy.",
		value: 50000,
		ingredients: [
			{
				id: "radon",
				name: "Radon",
				quantity: 250
			},
			{
				id: "condensed_carbon",
				name: "Condensed Carbon",
				quantity: 50
			}
		]
	},
	{
		id: "faecium", 
		name: "Faecium",
		type: "Raw Materials",
		description: "A foul-smelling compound that can be harvested from the Gutrot Flower, or less desirably from the faecal matter of some species. Creatures can be fed to encourage the formation and deposition of faecium crystals.",
		value: 30
	},
	{
		id: "ferrite_dust", 
		name: "Ferrite Dust",
		type: "Raw Materials",
		description: "An abundant mineral element, found in rock formations and other areas of geological interest. Easily extracted using a Mining Laser. Typically requires processing in a Refiner before use in construction or technology manufacture.",
		value: 14
	},
	{
		id: "frost_crystal",
		name: "Frost Crystal",
		type: "Raw Materials",
		description: "A beautiful blue crystal, this organic compound possesses both great hardiness and a shimmering translucence. It is harvested from the leaves of Frostwort. Frostwort requires frozen conditions to thrive in the wild, but can be farmed in all environments with the aid of a Hydroponics Tray.",
		value: 12
	},	
	{
		id: "fungal_mould",
		name: "Fungal Mould",
		type: "Raw Materials",
		description: "An oddly-glowing substance, harvested from the gills of Fungal Clusters. The host plant requires a toxic climate to thrive in the wild, but can be farmed in all environments with the aid of a Hydroponics Tray.",
		value: 16
	},
	{
		id: "fusion_accelerant",
		name: "Fusion Accelerant",
		type: "Crafted Products",
		description: "An advanced fuel source, made from a perfect blend of high potential energy organic materials.",
		value: 1500000,
		ingredients: [
			{
				id: "organic_catalyst",
				name: "Organic Catalyst",
				quantity: 1
			},
			{
				id: "nitrogen_salt",
				name: "Nitrogen Salt",
				quantity: 1
			}
		]
	},
	{
		id: "fusion_ignitor",
		name: "Fusion Ignitor",
		type: "Crafted Products",
		description: "A highly advanced piece of technology for use in the next generation of power plants. Producing a fusion core requires both intricate scientific skills and complex industrial processes.",
		value: 15600000,
		ingredients: [
			{
				id: "portable_reactor",
				name: "Portable Reactor",
				quantity: 1
			},
			{
				id: "quantum_processor",
				name: "Quantum Processor",
				quantity: 1
			},
			{
				id: "geodesite",
				name: "Geodesite",
				quantity: 1
			}
		]
	},
	{
		id: "gamma_root", 
		name: "Gamma Root",
		type: "Raw Materials",
		description: "A strange substance that seems to slowly shift the air around it. It is found in the roots of the Gamma Weed plant. Gamma Weed requires high background radiation to thrive in the wild, but can be farmed in all environments with the aid of a Hydroponics Tray.",
		value: 16
	},
	{
		id: "geodesite",
		name: "Geodesite",
		type: "Crafted Products",
		description: "Advanced and durable alloy primarily used in starship hull construction and deep-space exploration drone technology.",
		value: 150000,
		ingredients: [
			{
				id: "dirty_bronze",
				name: "Dirty Bronze",
				quantity: 1
			},
			{
				id: "herox",
				name: "Herox",
				quantity: 1
			},
			{
				id: "lemmium",
				name: "Lemmium",
				quantity: 1
			}
		]
	},
	{
		id: "glass",
		name: "Glass",
		type: "Crafted Products",
		description: "Shatter-proof, scratch-resistant glass with a self-cleaning, UV-cured coating, for general construction use.",
		value: 200,
		ingredients: [
			{
				id: "frost_crystal",
				name: "Frost Crystal",
				quantity: 250
			}
		]
	},	
	{
		id: "gold", 
		name: "Gold",
		type: "Raw Materials",
		description: "Highly valuable interstellar trading mineral, typically mined from asteroids. Occasionally found in underground planetary deposits. Universally prized for its beauty and versatility.",
		value: 353
	},
	{
		id: "grantine",
		name: "Grantine",
		type: "Crafted Products",
		description: "Soft workable alloy favored by artisans throughout the known galaxy. A popular trading good, with many galactic shipping paths devoted to its sale and transport.",
		value: 25000,
		ingredients: [
			{
				id: "dioxite",
				name: "Dioxite",
				quantity: 50
			},
			{
				id: "ionised_cobalt",
				name: "Ionised Cobalt",
				quantity: 50
			}
		]
	},
	{
		id: "heat_capacitor",
		name: "Heat Capacitor",
		type: "Crafted Products",
		description: "A thermal regulator produced from refined organic material. It is unique in its ability to produce, dissipate and distribute heat as required.",
		value: 180000,
		ingredients: [
			{
				id: "frost_crystal",
				name: "Frost Crystal",
				quantity: 100
			},
			{
				id: "solanium",
				name: "Solanium",
				quantity: 200
			}
		]
	},
	{
		id: "herox",
		name: "Herox",
		type: "Crafted Products",
		description: "Herox is a tradeable that can be crafted, found in containers or purchased.",
		value: 25000,
		ingredients: [
			{
				id: "ammonia",
				name: "Ammonia",
				quantity: 50
			},
			{
				id: "ionised_cobalt",
				name: "Ionised Cobalt",
				quantity: 50
			}
		]
	},
	{
		id: "hot_ice",
		name: "Hot Ice",
		type: "Crafted Products",
		description: "A paradoxical material, made less mysterious by its relative ease of manufacture.",
		value: 400000,
		ingredients: [
			{
				id: "enriched_carbon",
				name: "Enriched Carbon",
				quantity: 1
			}, 
			{
				id: "nitrogen_salt",
				name: "Nitrogen Salt",
				quantity: 1
			}
		]
	},
	{
		id: "indium",
		name: "Indium",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. Such stellar material ends up forming deposits in the crust of local planets. Indium is found on planets orbiting blue stars, and can be placed in a Refiner to create purified Chromatic Metal for use in the manufacture of advanced technologies.",
		value: 464
	},
	{
		id: "ionised_cobalt",
		name: "Ionised Cobalt",
		type: "Raw Materials",
		description: "A highly energised form of Cobalt, this processed metal can be used to create Advanced Ion Batteries, a conveniently portable source of energy for the Exosuit. In widespread use as a key component in the creation of advanced technologies and structures.",
		value: 401,
		ingredients: [
			{
				id: "cobalt",
				name: "Cobalt",
				quantity: 2
			}
		]

	},
	{
		id: "iridesite",
		name: "Iridesite",
		type: "Crafted Products",
		description: "Advanced light metal alloy traded throughout the galactic Outer Edge. Often used in the interiors of trading shuttles to reduce weight as they ascend from planets with high gravitational fields.",
		value: 150000,
		ingredients: [
			{
				id: "aronium",
				name: "Aronium",
				quantity: 1
			}, 
			{
				id: "magno_gold",
				name: "Magno Gold",
				quantity: 1
			}, 
			{
				id: "grantine",
				name: "Grantine",
				quantity: 1
			}
		]
	},
	{
		id: "kelp_sac",
		name: "Kelp Sac",
		type: "Raw Materials",
		description: "A rubbery, luminescent sac harvested from underwater Candle Kelp plants. Agricultural science has not yet tamed the Candle Kelp. As such, these sacs cannot be farmed.",
		value: 41
	},
	{
		id: "lemmium",
		name: "Lemmium",
		type: "Crafted Products",
		description: "Pure Ferrite alloy. Crafted from Pure Ferrite and Uranium. Used extensively in starship freighter construction due to its sheer strength. A hardcore material popular on the Galactic Trade Network.",
		value: 25000,
		ingredients: [
			{
				id: "uranium",
				name: "Uranium",
				quantity: 50
			}, 
			{
				id: "pure_ferrite",
				name: "Pure Ferrite",
				quantity: 100
			}
		]
	},
	{
		id: "living_glass",
		name: "Living Glass",
		type: "Crafted Products",
		description: "An advanced building material, this glass has been imbued with organic compounds that allow it to react to the environment. Microbes within the glass filter harmful light of all wavelengths and balance the atmosphere as required.",
		value: 566000,
		ingredients: [
			{
				id: "glass",
				name: "Glass",
				quantity: 5
			}, 
			{
				id: "lubricant",
				name: "Lubricant",
				quantity: 1
			}
		]
	},
	{
		id: "living_slime",
		name: "Living Slime",
		type: "Raw Materials",
		description: "A heavy, oozing slime. It is moving gently, as if it has a heartbeat of its own. Nutrient source: unknown.",
		value: 20
	},
	{
		id: "liquid_explosive",
		name: "Liquid Explosive",
		type: "Crafted Products",
		description: "A general purpose high explosive, offered in liquid form for convenience of transport and deployment. Do not drink.",
		value: 800500,
		ingredients: [
			{
				id: "acid",
				name: "Acid",
				quantity: 1
			}, 
			{
				id: "unstable_gel",
				name: "Unstable Gel",
				quantity: 1
			}
		]
	},
	{
		id: "lubricant",
		name: "Lubricant",
		type: "Crafted Products",
		description: "A synthetic lubricant that reduces wear and prolongs the lifespan of technologies with moving parts.",
		value: 110000,
		ingredients: [
			{
				id: "gamma_root",
				name: "Gamma Root",
				quantity: 400
			}, 
			{
				id: "faecium",
				name: "Faecium",
				quantity: 50
			}
		]
	},
	{
		id: "magnetised_ferrite",
		name: "Magnetised Ferrite",
		type: "Raw Materials",
		description: "Highly processed metal, requiring several stages of processing in a Refiner. Used in the creation of advanced structures and technologies. Avoid ingestion.",
		value: 82
	},
	{
		id: "magno_gold",
		name: "Magno-Gold",
		type: "Crafted Products",
		description: "Highly prized and lustrous alloy. Popular with traders of all known primary galactic races. Crafted from Ionised Cobalt and Phosphorus. Easily recognisable by its bright red glow and strong magnetic field.",
		value: 25000,
		ingredients: [
			{
				id: "phosphorus",
				name: "Phosphorus",
				quantity: 50
			}, 
			{
				id: "ionised_cobalt",
				name: "Ionised Cobalt",
				quantity: 50
			}
		]
	},
	{
		id: "marrow_bulb",
		name: "Marrow Bulb",
		type: "Raw Materials",
		description: "A glowing organic bulb, harvested from the Cave Marrow plant found growing underground. The Cave Marrow has proved resistant to domestication, and no farmable cultivars are known to exist. As such, marrow bulbs must be harvested by hand in the wild.",
		value: 41
	},
	{
		id: "mordite",
		name: "Mordite",
		type: "Raw Materials",
		description: "Despite much study, little is known about this haunting, crystalline compound. It is released from the cadavers of dying creatures, but can also be specifically cultivated and harvested from the Mordite Root plant.",
		value: 40
	},
	{
		id: "nitrogen", 
		name: "Nitrogen",
		type: "Raw Materials",
		description: "A reactive atmospheric gas found wherever there is organic life. Nitrogen is readily harvested from the atmospheres of Lush and Toxic planets.",
		value: 20
	},
	{
		id: "nitrogen_salt",
		name: "Nitrogen Salt",
		type: "Crafted Products",
		description: "A refined product, this is a powerful organic fertiliser in an easily distributed form.",
		value: 50000,
		ingredients: [
			{
				id: "nitrogen",
				name: "Nitrogen",
				quantity: 250
			}, 
			{
				id: "condensed_carbon",
				name: "Condensed Carbon",
				quantity: 50
			}
		]
	},
	{
		id: "organic_catalyst",
		name: "Organic Catalyst",
		type: "Crafted Products",
		description: "A catalytic material used in the creation of many organic fertilizers.",
		value: 320000,
		ingredients: [
			{
				id: "thermic_condensate",
				name: "Thermic Condensate",
				quantity: 1
			}, 
			{
				id: "enriched_carbon",
				name: "Enriched Carbon",
				quantity: 1
			}
		]
	},
	{
		id: "oxygen",
		name: "Oxygen",
		type: "Raw Materials",
		description: "Integral to the atmospheric filtering technology at the heart of the exosuit life support system.	Exosuit material processing allows oxygen to be harvested directly from appropriate planetary flora. Other plantlife may be scanned with the Analysis Visor to reveal alternative oxygen supplies.",
		value: 34
	},
	{
		id: "paraffinium",
		name: "Paraffinium",
		type: "Raw Materials",
		description: "Local mineral extract, typically found in large deposits or extracted from common materials after inspection with an Analysis Visor. Typically found on planets with a tropical environment.",
		value: 62
	},
	{
		id: "phosphorus",
		name: "Phosphorus",
		type: "Raw Materials",
		description: "Local mineral extract, typically found in large deposits or extracted from common minerals after inspection with an Analysis Visor. Typically found on planets with a scorched environment.",
		value: 62
	},
	{
		id: "platinum",
		name: "Platinum",
		type: "Raw Materials",
		description: "Extremely valuable interstellar trading mineral, typically mined from asteroids. Occasionally found in underground planetary deposits. Universally prized for its hardiness and versatility.",
		value: 505
	},
	{
		id: "poly_fibre", 
		name: "Poly Fibre",
		type: "Advanced Agricultural Product",
		description: "A connective fibre for electronics, made from an advanced synthetic polymer and capable of serving as a conduit for power and data.",
		value: 130000,
		ingredients: [
			{
				id: "cactus_flesh",
				name: "Cactus Flesh",
				quantity: 100
			},
			{
				id: "star_bulb",
				name: "Star Bulb",
				quantity: 200
			}
		]
	},
	{
		id: "portable_reactor",
		name: "Portable Reactor",
		type: "Crafted Products",
		description: "A miniature self-controlled nuclear reactor. Generates sub-stellar levels of energy in a hassle-free, widely compatible fuel module.",
		value: 4200000,
		ingredients: [
			{
				id: "liquid_explosive",
				name: "Liquid Explosive",
				quantity: 1
			}, 
			{
				id: "fusion_accelerant",
				name: "Fusion Accelerant",
				quantity: 1
			}
		]
	},
	{
		id: "pugneum",
		name: "Pugneum",
		type: "Raw Materials",
		description: "This oily, unsettling liquid leaks from the circuitry of Sentinels. Prized by the Vy'keen, Pugneum is thought to share some essential properties with Nanites. It hums in a sinister fashion upon contact with organic matter.",
		value: 138
	},
	{
		id: "pure_ferrite",
		name: "Pure Ferrite",
		type: "Raw Materials",
		description: "Processed metal, free of dust and pebbles. Used to construct a wide variety of structures and technologies. Typically purified from Ferrite dust using a Refiner, but can occasionally be found in large deposits. Collection may require an Advanced Mining Laser.",
		value: 138
	},
	{
		id: "pyrite",
		name: "Pyrite",
		type: "Raw Materials",
		description: "Local mineral extract, typically found in large deposits or extracted from common materials after inspection with an Analysis Visor. Typically found on planets with a desert environment.",
		value: 62
	},
	{
		id: "quantum_processor",
		name: "Quantum Processor",
		type: "Crafted Products",
		description: "A highly advanced computational device, essential for the complex calculations involved in warp travel.",
		value: 5200000,
		ingredients: [
			{
				id: "circuit_board",
				name: "Circuit Board",
				quantity: 1
			}, 
			{
				id: "superconductor",
				name: "Superconductor",
				quantity: 1
			}
		]
	},
	{
		id: "radon",
		name: "Radon",
		type: "Raw Materials",
		description: "A colourless, odourless gas with a relatively short half-life. Found in both Radioactive and Frozen atmospheres, this gas is produced by the decay of other high-energy elements.",
		value: 20
	},
	{
		id: "residual_goop",
		name: "Residual Goop",
		type: "Raw Materials",
		description: "A pulsating, foul smelling goop that builds up in poorly-maintained machinery. Skin contact is not advised.",
		value: 20
	},
	{
		id: "runaway_mould",
		name: "Runaway Mould",
		type: "Raw Materials",
		description: "An out of control mould growth that builds up in poorly-maintained machinery. Likely to be several different species of mould, merged together into one super-colony.",
		value: 20
	},
	{
		id: "rusted_metal",
		name: "Rusted Metal",
		type: "Raw Materials",
		description: "Handfulls of corroded metal, distorted by years of exposure to the harsh environment. Handle with care.",
		value: 20
	},
	{
		id: "salt",
		name: "Salt",
		type: "Raw Materials",
		description: "A naturally occuring salt, found in abundance in underwater minerals. Can be processed in a Refiner to create Chlorine. This refined form is used in the manufacture of advanced products and technologies.",
		value: 299
	},
	{
		id: "silicate_powder",
		name: "Silicate Powder",
		type: "Raw Materials",
		description: "An abundant mineral element, found within the geological strata of all rocky worlds. Easily extracted using a Terrain Manipulator. Create a tunnel anywhere to begin extraction. Process in a Refiner to create Glass.",
		value: 2
	},
	{
		id: "silver",
		name: "Silver",
		type: "Raw Materials",
		description: "Valuable interstellar trading mineral, typically mined from asteroids. Occasionally found in underground planetary deposits. Prized by people in all systems for its lustre and shine.",
		value: 186
	},
	{
		id: "semiconductor",
		name: "Semiconductor",
		type: "Crafted Products",
		description: "An advanced material useful in many electronic devices, with its own in-built temperature regulator. Crafted from Thermic Condensate and Nitrogen Salt.",
		value: 15600000,
		ingredients: [
			{
				id: "thermic_condensate",
				name: "Thermic Condensate",
				quantity: 1 
			},
			{
				id: "nitrogen_salt",
				name: "Nitrogen Salt",
				quantity: 1
			}
		]
	},
	{
		id: "sodium",
		name: "Sodium",
		type: "Raw Materials",
		description: "A powerful catalyst, useful for charging defensive technologies such as shields or hazard protection. Exosuit material handling technology allows automatic harvesting from appropriate sodium-rich flora. A vital ingredient in the creation of many advanced devices, products and components.",
		value: 41
	},
	{
		id: "sodium_nitrate",
		name: "Sodium Nitrate",
		type: "Raw Materials",
		description: "An advanced catalyst, useful for charging defensive technologies such as shields or hazard protection. Created in a Refiner, or occasionally found in crystalline form on a planet's surface. Offers a substantially improved energy-per-gram ratio over regular Sodium.",
		value: 82
	},
	{
		id: "solanium",
		name: "Solanium",
		type: "Raw Materials",
		description: "A powerful chemical that has resisted attempts at synthesis. It can be harvested from the bark of the Solar Vine. The vine requires a hot climate to thrive in the wild, but can be farmed in all environments with the aid of a Hydroponics Tray.",
		value: 70
	},
	{
		id: "star_bulb",
		name: "Star Bulb",
		type: "Raw Materials",
		description: "A beautiful gemstone, this prized product is the engorged, luminescent berry of the Star Bramble. The host plant requires lush conditions to thrive in the wild but can be farmed in all environments with the aid of a Hydroponic Tray.",
		value: 32
	},
	{
		id: "sulphurine", 
		name: "Sulphurine",
		type: "Raw Materials",
		description: "A pungent atmospheric gas. High concentrations are extremely hazardous to organic life. With the aid of specialised machinery, can be extracted from the atmospheres of Scorched and Desert planets.",
		value: 20
	},
	{
		id: "stasis_device",
		name: "Stasis Device",
		type: "Crafted Products",
		description: "A device specifically crafted to keep lifeforms alive for thousands of years longer than their natural lifespan. Such a device requires great skill to manufacture, as not only is it technically complex, but the consequences for a user in the event of malfunction would be disastrous.",
		value: 15600000,
		ingredients: [
			{
				id: "quantum_processor",
				name: "Quantum Processor",
				quantity: 1 
			},
			{
				id: "cryogenic_chamber",
				name: "Cryogenic Chamber",
				quantity: 1
			},
			{
				id: "iridesite",
				name: "Iridesite",
				quantity: 1 
			}
		]
	},
	{
		id: "superconductor",
		name: "Superconductor",
		type: "Crafted Products",
		description: "An advanced conductive material, the superconductor further enriches the field-warping power of the Semiconductor.",
		value: 2000000,
		ingredients: [
			{
				id: "enriched_carbon",
				name: "Enriched Carbon",
				quantity: 1
			},
			{
				id: "semiconductor",
				name: "Semiconductor",
				quantity: 1
			}
		]
	},
	{
		id: "tainted_metal",
		name: "Tainted Metal",
		type: "Raw Materials",
		description: "Shredded fragments of a soft, grey metal. Its surface is porous, and when touched it oozes ever-so-slightly. Found in the creaking wreck of a derelict freighter. The space station Scrap Dealer may find this interesting...",
		value: 380
	},
	{
		id: "thermic_condensate",
		name: "Thermic Condensate",
		type: "Crafted Products",
		description: "A refined product, holding the energy potential of heated atmospheric gas in a stable state until required.",
		value: 50000,
		ingredients: [
			{
				id: "sulphurine",
				name: "Sulphurine",
				quantity: 250
			}, 
			{
				id: "condensed_carbon",
				name: "Condensed Carbon",
				quantity: 50
			}
		]
	},
	{
		id: "tritium",
		name: "Tritium",
		type: "Raw Materials",
		description: "Radioactive isotope commonly used to fuel the fusion reactor at the heart of starship Pulse Engines. Abundant in interstellar asteroid fields, Tritium can be mined from asteroids using starship weaponry.",
		value: 6
	},
	{
		id: "unstable_gel",
		name: "Unstable Gel",
		type: "Crafted Products",
		description: "A highly reactive gel, this substance is both energy-rich and dangerous to touch.",
		value: 50000,
		ingredients: [
			{
				id: "cactus_flesh",
				name: "Cactus Flesh",
				quantity: 200
			}
		]
	},
	{
		id: "uranium",
		name: "Uranium",
		type: "Raw Materials",
		description: "Local mineral extract, typically found in large deposits or extracted from common minerals after inspection with an Analysis Visor. Typically found on planets with a radioactive environment.",
		value: 62
	},
	{
		id: "viscous_fluids",
		name: "Viscous Fluids",
		type: "Raw Materials",
		description: "An unnaturally thick liquid of dubious colour. Its origins are impossible to fathom. Appears to have some mild magnetic properties.",
		value: 20
	}
];

// todo: fill in missing data 
// todo: fill in missing color data for new resources 
// todo: refactor css item ids into classes?

var app = new Vue({
    el: '#app',
    data: {
		items: items,
		selected_item: "stasis_device",
		filter: ''
    },
    methods: {
		load_item: function(item_id){
			this.selected_item = item_id;
		},
		toggleDrawer: function(drawerClass){
			var drawer = document.querySelector(`.${drawerClass} .drawer`);
			if(drawer.style.display == 'block'){
				drawer.style.display = 'none';
			} else {
				drawer.style.display = 'block';
			}
		}
    },
	computed: {
		item_selected(){
			return this.items.filter(item => {
				return item.id === this.selected_item;
			})
		},
		items_filtered() {
			return this.items.filter(item => {
				return item.name.toLowerCase().indexOf(this.filter.toLowerCase()) > -1;
			})
		},
		items_raw_materials() {
			return this.items.filter(item => {
				return item.type === "Raw Materials";
			})
		},
		items_crafted_products() {
			return this.items.filter(item => {
				return item.type === "Crafted Products";
			})
		}
	},
	beforeMount(){},
	mounted(){},
	updated(){}
})