/*
|--------------------------------------------------------------------------
| DATA > CRAFTING
|--------------------------------------------------------------------------
*/
var items = [
	{
		id: "acid",
		name: "Acid",
		type: "Crafted Products",
		description: "Dilute acid for high current generation in diverse power cells.",
		value: 188000,
		ingredients: [
			{
				id: "mordite",
				name: "Mordite",
				quantity: 25
			}, 
			{
				id: "fungal_mould",
				name: "Fungal Mould",
				quantity: 600
			}
		]
	},
	{
		id: "activated_cadmium",
		name: "Activated Cadmium",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. This Cadmium has been activated by the extreme conditions in which it was formed, and is highly valuable. Cadmium is found on planets orbiting red stars, and can be placed in a Refiner to create purified Chromatic Metal.",
		value: 450
	},
	{
		id: "activated_copper",
		name: "Activated Copper",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. This Copper has been activated by the extreme conditions in which it was formed, and is highly valuable. Copper is found on planets orbiting yellow stars, and can be placed in a Refiner to create purified Chromatic Metal.",
		value: 245
	},
	{
		id: "activated_emeril",
		name: "Activated Emeril",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. This Emeril has been activated by the extreme conditions in which it was formed, and is highly valuable. Emeril is found on planets orbiting green stars, and can be placed in a Refiner to create purified Chromatic Metal.",
		value: 696
	},
	{
		id: "activated_indium",
		name: "Activated Indium",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. Indium is found on planets orbiting blue stars, and can be placed in a Refiner to create purified Chromatic Metal. This Indium has been activated by the extreme conditions in which it was formed, and is highly valuable.",
		value: 949
	},
	{
		id: "albumen_pearl",
		name: "Albumen Pearl",
		type: "Curiosities",
		description: "Gemstone formed over the course of centuries within the egg of a super-incubatory species. Extremely rare.",
		value: 10640
	},
	{
		id: "albumen_pearl_orb",
		name: "Albumen Pearl Orb",
		type: "Crafted Products",
		description: "A medium-sized, farmable Crystal Orb that yields an occasional harvest of valuable Albumen Pearls. Suitable for hydroponic indoor planting. Cannot be planted outdoors. Approximate growing time: 2 hours",
		value: 3
	},
	{
		id: "anomaly_detector",
		name: "Anomaly Detector",
		type: "Curiosities",
		description: "A single-use geometric beacon that probes the surrounding area for near-space anomalies. Such objects are highly unpredictable. Select the Detector and use Begin Scan to begin the location process.",
		value: 3280
	},
	{
		id: "antimatter",
		name: "Antimatter",
		type: "Crafted Products",
		description: "Contained negative matter and baryogenesis antiparticles. The vast energy potential of antimatter makes it highly valuable. 95% of existing antimatter consumption is in the powering of starship hyperdrives. WARNING: uncontained usage is not recommended.",
		value: 5233
	},
	{
		id: "antimatter_housing",
		name: "Antimatter Housing",
		type: "Crafted Products",
		description: "Secure antimatter containment device, required before Antimatter can be safely secured as Warp Cells. Rebound Oxygen forms a protective gas pocket, preventing the antimatter from reacting with the surrounding casing.",
		value: 6500
	},
	{
		id: "aronium",
		name: "Aronium",
		type: "Raw Materials",
		description: "A lightweight and highly malleable alloy. Crafted from Paraffinium and Chlorine. In high demand on the Galactic Trade Network due to its utility in the construction of planetside outposts and facilities.",
		value: 25000,
		ingredients: [
			{
				id: "paraffinium",
				name: "Paraffinium",
				quantity: 50
			}, 
			{
				id: "ionised_cobalt",
				name: "Ionised Cobalt",
				quantity: 50
			}
		]
	},
	{
		id: "basalt",
		name: "Basalt",
		type: "Raw Materials",
		description: "Local mineral extract, typically found in large deposits or extracted from common minerals after inspection with an Analysis Visor. Typically found on planets with a volcanic environment.",
		value: 62
	},
	{
		id: "cactus_flesh",
		name: "Cactus Flesh",
		type: "Raw Materials",
		description: "Succulent, edible cactus flesh from the Echinocactus plant. As well as being juicy on the tongue, the flesh has many industrial uses. The Echinocactus thrives only on desert planets, but can be farmed in all environments with the aid of a Hydroponics Tray.",
		value: 28
	},
	{
		id: "cadmium",
		name: "Cadmium",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. Such stellar material ends up forming deposits in the crust of local planets. Cadmium is found on planets orbiting red stars, and can be placed in a Refiner to create purified Chromatic Metal for use in the manufacture of advanced technologies.",
		value: 234
	},
	{
		id: "captured_nanode",
		name: "Captured Nanode",
		type: "Curiosities",
		description: "Atlas Seed containing zonally-shifted quasi-stellar substrate. Warning: do not allow matrix to commune with this dimensional space.",
		value: 1000
	},
	{
		id: "carbon",
		name: "Carbon",
		type: "Raw Materials",
		description: "The building block of all organic life. Of critical importance to space travelers, as Carbon is used to recharge mining equipment. The Mining Laser will harvest Carbon from trees, plants, and all other forms of vegetation.",
		value: 12
	},
	{
		id: "carbon_nanotubes",
		name: "Carbon Nanotubes",
		type: "Crafted Products",
		description: "Metres and metres of high capacity carbon nanotubes. Their high tensile strength and mild conductivity make these a key component in many advanced technologies.",
		value: 500
	},
	{
		id: "chlorine",
		name: "Chlorine",
		type: "Raw Materials",
		description: "A reactive element most easily harvested by processing the salt-infused minerals found in oceans. Used in the manufacture of advanced technologies.",
		value: 602
	},	
	{
		id: "chromatic_metal", 
		name: "Chromatic Metal",
		type: "Raw Materials",
		description: "A processed metal alloy, created in a Refiner from the stellar metals: Copper, Cadmium, Emeril and Indium. The rarer the stellar metal, the more Chromatic Metal it will produce. This valuable metal is used in the creation of many advanced technologies.",
		value: 245
	},
	{
		id: "circuit_board",
		name: "Circuit Board",
		type: "Crafted Products",
		description: "Stackable, semi-flexible circuit board made from a highly durable synthetic polymer.",
		value: 916250,
		ingredients: [
			{
				id: "poly_fibre",
				name: "Poly Fibre",
				quantity: 1
			},
			{
				id: "heat_capacitor",
				name: "Heat Capacitor",
				quantity: 1
			}
		]
	},	
	{
		id: "cobalt", 
		name: "Cobalt",
		type: "Raw Materials",
		description: "Mined from underground minerals, cobalt is found in plentiful supply in caves and caverns. Useful in the manufacture of Ion Batteries. It is used in the creation of several technologies and structures, and can be processed in a Refiner to make the most of its inherent charge.",
		value: 198
	},
	{
		id: "condensed_carbon", 
		name: "Condensed Carbon",
		type: "Raw Materials",
		description: "Advanced material, processed from regular carbon in a Refiner. The increased molecule density offers a substantially improved energy-per-gram ratio. Occasionally found in crystalline form. Harvesting large crystals may require an Advanced Mining Laser.",
		value: 24,
		ingredients: [
			{
				id: "carbon",
				name: "Carbon",
				quantity: 2
			}
		]
	},
	{
		id: "copper",
		name: "Copper",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. Such stellar material ends up forming deposits in the crust of local planets. Copper is found on planets orbiting yellow stars, and can be placed in a Refiner to create purified Chromatic Metal for use in the manufacture of advanced technologies.",
		value: 121
	},
	{
		id: "cryo_pump",
		name: "Cryo-Pump",
		type: "Crafted Products",
		description: "An advanced, self-regulating hybrid material, the Cryo-Pump distributes heat across itself with near perfect efficiency, making it vital in the creation of thermal regulators.",
		value: 1500000,
		ingredients: [
			{
				id: "hot_ice",
				name: "Hot Ice",
				quantity: 1
			}, 
			{
				id: "thermic_condensate",
				name: "Thermic Condensate",
				quantity: 1
			}
		]
	},
	{
		id: "cryogenic_chamber",
		name: "Cryogenic Chamber",
		type: "Crafted Products",
		description: "A low temperature chamber, designed to prevent the natural decay of organic matter.",
		value: 3800000,
		ingredients: [
			{
				id: "living_glass",
				name: "Living Glass",
				quantity: 1
			}, 
			{
				id: "cryo_pump",
				name: "Cryo-Pump",
				quantity: 1
			}
		]
	},
	{
		id: "crystal_fragment",
		name: "Crystal Fragment",
		type: "Curiosities",
		description: "A crystalline shard with an unusually dense structure. Potentially highly valuable.",
		value: 3280
	},
	{
		id: "crystal_sulphide",
		name: "Crystal Sulphide",
		type: "Curiosities",
		description: "Formed in the incredible, high-pressure furnace of planetary cores, these rich mineral deposits have an almost glass-like quality. Has a wide variety of industrial uses, taking advantage of both its mineral content and its extreme strength under pressure.",
		value: 7410
	},
	{
		id: "cyto_phosphate",
		name: "Cyto-Phosphate",
		type: "Raw Materials",
		description: "A blue-green organic compound produced during the metabolic cycle of deep-sea plantlife. Rich in soluble energy, cyto-phosphates are crucial in many submarine technologies. The Mining Laser will harvest cyto-phosphate compounds from underwater flora.",
		value: 201
	},
	{
		id: "dark_matter",
		name: "Dark Matter",
		type: "Curiosities",
		description: "An Atlas Seed shell encompassing a void element harvested from the collapse state of the last universe. Toxic if ingested.",
		value: 1000
	},
	{
		id: "dawns_end",
		name: "Dawn's End",
		type: "Curiosities",
		description: "Sculpted tau neutrino-boson matrix fixed within an irreplaceable Atlas Seed shell. May be semi-sentient.",
		value: 1000
	},
	{
		id: "deuterium",
		name: "Deuterium",
		type: "Raw Materials",
		description: "A stable hydrogen isotope used heavily in both small-scale fusion reactors and neutron-scattering shield technology. Deuterium very rarely occurs naturally. Most of the galaxy's supply comes from the processing of Di-hydrogen and Tritium in Refiners.",
		value: 34
	},
	{
		id: "di_hydrogen",
		name: "Di-hydrogen",
		type: "Raw Materials",
		description: "A stable, crystalline form of hydrogen remarkable both for its extreme energy density and its stability at atmospheric pressures. Common to all worlds, Di-hydrogen is found in the form of large blue crystals. It is a key component of Starship Launch Fuel.",
		value: 34
	},
	{
		id: "di_hydrogen_jelly",
		name: "Di-hydrogen Jelly",
		type: "Crafted Products",
		description: "A faintly-glowing jelly. Its gentle light and soft wobble belie the fact that this sticky gel is both highly toxic and highly flammable. Skin contact is to be avoided at all costs. Synthesised from Di-hydrogen.",
		value: 200
	},
	{
		id: "dioxite",
		name: "Dioxite",
		type: "Raw Materials",
		description: "Local mineral extract, typically found in large deposits or extracted from common minerals after inspection with an Analysis Visor. Typically found on planets with a frozen environment.",
		value: 62
	},
	{
		id: "dirty_bronze",
		name: "Dirty Bronze",
		type: "Crafted Products",
		description: "A popular metal alloy with a wide variety of uses. 'Dirty Bronze' has shed its scientific name in favor of the popular term for its colour.",
		value: 25000,
		ingredients: [
			{
				id: "pyrite",
				name: "Pyrite",
				quantity: 50
			}, 
			{
				id: "pure_ferrite",
				name: "Pure Ferrite",
				quantity: 100
			}
		]
	},
	{
		id: "divergence_cube",
		name: "Divergence Cube",
		type: "Curiosities",
		description: "A glitching, pulsing data unit. It does not seem to belong in this reality. The cube gives the impression of a silent scream, the frozen cries of hundreds of lost minds trapped within.",
		value: 3015
	},
	{
		id: "echinocactus",
		name: "Echinocactus",
		type: "Crafted Products",
		description: "Native to barren biomes and capable of withstanding long periods of drought, Echinocactus is an edible succulent that responds well to cultivation, yielding a large but occasional harvest. Suitable for hydroponic indoor planting. Ensure Barren climate before planting outdoors. Approximate growing time: 16 hours",
		value: 3
	},
	{
		id: "emergency_broadcast_receiver",
		name: "Emergency Broadcast Receiver",
		type: "Curiosities",
		description: "A single-use receiver that scans for distress signals on freighter frequencies. Derelict or abandoned freighters often contain high-value salvage. Select the Receiver and use Tune Signal to begin the location process.",
		value: 3280
	},
	{
		id: "emeril",
		name: "Emeril",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. Emeril is found on planets orbiting green stars, and can be placed in a Refiner to create purified Chromatic Metal for use in the manufacture of advanced technologies.",
		value: 348
	},
	{
		id: "englobed_shade",
		name: "Englobed Shade",
		type: "Curiosities",
		description: "This Atlas Shell holds the remains of a parasitic space-borne lifeform, most likely of extra-dimensional origins.",
		value: 1000
	},
	{
		id: "enriched_carbon",
		name: "Enriched Carbon",
		type: "Crafted Products",
		description: "A refined product, taking ordinary carbon and boosting it with radioactive energy.",
		value: 50000,
		ingredients: [
			{
				id: "radon",
				name: "Radon",
				quantity: 250
			},
			{
				id: "condensed_carbon",
				name: "Condensed Carbon",
				quantity: 50
			}
		]
	},
	{
		id: "explosive_drones",
		name: "Explosive Drones",
		type: "Crafted Products",
		description: "A temporary frigate upgrade that lasts for one expedition. This pack of autonomous explosives have been programmed to launch from the fleet and pilot themselves directly towards hostile vessels. Extremely dangerous.",
		value: 75000
	},
	{
		id: "faecium", 
		name: "Faecium",
		type: "Raw Materials",
		description: "A foul-smelling compound that can be harvested from the Gutrot Flower, or less desirably from the faecal matter of some species. Creatures can be fed to encourage the formation and deposition of faecium crystals.",
		value: 30
	},
	{
		id: "ferrite_dust", 
		name: "Ferrite Dust",
		type: "Raw Materials",
		description: "An abundant mineral element, found in rock formations and other areas of geological interest. Easily extracted using a Mining Laser. Typically requires processing in a Refiner before use in construction or technology manufacture.",
		value: 14
	},
	{
		id: "frigate_fuel_50_tonnes",
		name: "Frigate Fuel (50 Tonnes)",
		type: "Crafted Products",
		description: "A small barrel of frigate fuel. This viscous gel is highly toxic to the touch. A refined fuel, it powers the interstellar engines of large trading ships.",
		value: 20000
	},
	{
		id: "frigate_fuel_100_tonnes",
		name: "Frigate Fuel (100 Tonnes)",
		type: "Crafted Products",
		description: "A large barrel of frigate fuel. This viscous gel is highly toxic to the touch. A refined fuel, it powers the interstellar engines of large trading ships.",
		value: 40000
	},
	{
		id: "frigate_fuel_200_tonnes",
		name: "Frigate Fuel (200 Tonnes)",
		type: "Crafted Products",
		description: "A huge barrel of frigate fuel. This viscous gel is highly toxic to the touch. A refined fuel, it powers the interstellar engines of large trading ships.",
		value: 80000
	},
	{
		id: "frost_crystal",
		name: "Frost Crystal",
		type: "Raw Materials",
		description: "A beautiful blue crystal, this organic compound possesses both great hardiness and a shimmering translucence. It is harvested from the leaves of Frostwort. Frostwort requires frozen conditions to thrive in the wild, but can be farmed in all environments with the aid of a Hydroponics Tray.",
		value: 12
	},
	{
		id: "frostwort",
		name: "Frostwort",
		type: "Crafted Products",
		description: "A large crystal flower with radiant blue blooms, found only in snowy biomes. Frostwort can be farmed and makes a reliable crop, and its adaptation to harsh conditions results in highly frequent harvests. Suitable for hydroponic indoor planting. Ensure Frozen climate before planting outdoors. Approximate growing time: 1 hour",
		value: 3
	},	
	{
		id: "fungal_cluster",
		name: "Fungal Cluster",
		type: "Crafted Products",
		description: "A spherical fungus with internal gills, found only in toxic biomes. Fungal Clusters can be transplanted for cultivation, yielding a bountiful harvest. Suitable for hydroponic indoor planting. Ensure Toxic climate before planting outdoors. Approximate growing time: 4 hours",
		value: 3
	},
	{
		id: "fungal_mould",
		name: "Fungal Mould",
		type: "Raw Materials",
		description: "An oddly-glowing substance, harvested from the gills of Fungal Clusters. The host plant requires a toxic climate to thrive in the wild, but can be farmed in all environments with the aid of a Hydroponics Tray.",
		value: 16
	},
	{
		id: "fuel_oxidiser",
		name: "Fuel Oxidiser",
		type: "Crafted Products",
		description: "A temporary frigate upgrade that lasts for one expedition. This powerful fuel upgrade overloads frigate engines, allowing for faster-than-usual travel.",
		value: 75000
	},
	{
		id: "fusion_accelerant",
		name: "Fusion Accelerant",
		type: "Crafted Products",
		description: "An advanced fuel source, made from a perfect blend of high potential energy organic materials.",
		value: 1500000,
		ingredients: [
			{
				id: "organic_catalyst",
				name: "Organic Catalyst",
				quantity: 1
			},
			{
				id: "nitrogen_salt",
				name: "Nitrogen Salt",
				quantity: 1
			}
		]
	},
	{
		id: "fusion_ignitor",
		name: "Fusion Ignitor",
		type: "Crafted Products",
		description: "A highly advanced piece of technology for use in the next generation of power plants. Producing a fusion core requires both intricate scientific skills and complex industrial processes.",
		value: 15600000,
		ingredients: [
			{
				id: "portable_reactor",
				name: "Portable Reactor",
				quantity: 1
			},
			{
				id: "quantum_processor",
				name: "Quantum Processor",
				quantity: 1
			},
			{
				id: "geodesite",
				name: "Geodesite",
				quantity: 1
			}
		]
	},
	{
		id: "gamma_root", 
		name: "Gamma Root",
		type: "Raw Materials",
		description: "A strange substance that seems to slowly shift the air around it. It is found in the roots of the Gamma Weed plant. Gamma Weed requires high background radiation to thrive in the wild, but can be farmed in all environments with the aid of a Hydroponics Tray.",
		value: 16
	},
	{
		id: "gamma_weed",
		name: "Gamma Weed",
		type: "Crafted Products",
		description: "A luminous, leafy flowering plant that thrives in radioactive biomes and can be cultivated to yield a bountiful harvest. Suitable for hydroponic indoor planting. Ensure Radioactive climate before planting outdoors. Approximate growing time: 4 hours",
		value: 16
	},
	{
		id: "gek_relic",
		name: "Gek Relic",
		type: "Curiosities",
		description: "A metal statuette of a creature with a coin placed in its beak. Popular with many traders who see it as an emblem of fair commerce and peace.",
		value: 23375
	},
	{
		id: "geknip",
		name: "GekNip",
		type: "Curiosities",
		description: "Edible product much beloved by the Gek. Allows beaked traders to release delightfully scented packets of gas for a prolonged period of time. GekNip gas packets are considered an art form, and the truest representation of the Gek soul.",
		value: 20625
	},
	{
		id: "geode",
		name: "Geode",
		type: "Curiosities",
		description: "An unusually vibrant and potentially valuable lump of rock.",
		value: 3280
	},
	{
		id: "geodesite",
		name: "Geodesite",
		type: "Crafted Products",
		description: "Advanced and durable alloy primarily used in starship hull construction and deep-space exploration drone technology.",
		value: 150000,
		ingredients: [
			{
				id: "dirty_bronze",
				name: "Dirty Bronze",
				quantity: 1
			},
			{
				id: "herox",
				name: "Herox",
				quantity: 1
			},
			{
				id: "lemmium",
				name: "Lemmium",
				quantity: 1
			}
		]
	},
	{
		id: "glass",
		name: "Glass",
		type: "Crafted Products",
		description: "Shatter-proof, scratch-resistant glass with a self-cleaning, UV-cured coating, for general construction use.",
		value: 200,
		ingredients: [
			{
				id: "frost_crystal",
				name: "Frost Crystal",
				quantity: 250
			}
		]
	},
	{
		id: "glowing_mineral",
		name: "Glowing Mineral",
		type: "Curiosities",
		description: "Though its surface is dirtied and dull, polishing this rock reveals a deep inner glow, a glitter beneath a subtly iridescent surface.",
		value: 3280
	},
	{
		id: "gold", 
		name: "Gold",
		type: "Raw Materials",
		description: "Highly valuable interstellar trading mineral, typically mined from asteroids. Occasionally found in underground planetary deposits. Universally prized for its beauty and versatility.",
		value: 353
	},
	{
		id: "gold_nugget",
		name: "Gold Nugget",
		type: "Curiosities",
		description: "A highly valuable ore chunk, ready to be processed into Gold.",
		value: 3280
	},
	{
		id: "grantine",
		name: "Grantine",
		type: "Crafted Products",
		description: "Soft workable alloy favored by artisans throughout the known galaxy. A popular trading good, with many galactic shipping paths devoted to its sale and transport.",
		value: 25000,
		ingredients: [
			{
				id: "dioxite",
				name: "Dioxite",
				quantity: 50
			},
			{
				id: "ionised_cobalt",
				name: "Ionised Cobalt",
				quantity: 50
			}
		]
	},
	{
		id: "gravitino_ball",
		name: "Gravitino Ball",
		type: "Curiosities",
		description: "A supersymmetric particle cluster created by divergent super-gravitational forces. A micro-rift is created as they form, and extraction of the orb prompts a localised reality weakening. Sentinel forces will respond to stablise any such anomaly. Can be sold at a Galactic Trade Terminal.",
		value: 40024
	},
	{
		id: "gravitino_host",
		name: "Gravitino Host",
		type: "Crafted Products",
		description: "A strange, potentially parasitic plant that yields an occasional harvest of the highly tradable commodity, Gravitino Balls. Suitable for hydroponic indoor planting. Cannot be planted outdoors. Approximate growing time: 2 hours",
		value: 3
	},
	{
		id: "gutrot_flower",
		name: "Gutrot Flower",
		type: "Crafted Products",
		description: "A foul-smelling, farmable flower that replicates the chemical structure of faecal matter. When planted inside, yields a harvest of Faecium. A good alternative to collecting Faecium by hand, which requires feeding creatures and then harvesting their droppings. Gutrot Flowers must be grown in a Hydroponics Tray. Approximate growing time: 4 hours",
		value: 3
	},
	{
		id: "hadal_core",
		name: "Hadal Core",
		type: "Curiosities",
		description: "A highly-pressurised fleshy orb. One can feel it push back when touched, a flash of bioluminescence stirring in the inky black core of this mysterious object.",
		value: 92625
	},
	{
		id: "heart_of_the_sun",
		name: "Heart of the Sun",
		type: "Curiosities",
		description: "An Atlas Seed containing a time-locked quantum cilia suspended in a photonic shell. No others are known to exist.",
		value: 1000
	},
	{
		id: "heat_capacitor",
		name: "Heat Capacitor",
		type: "Crafted Products",
		description: "A thermal regulator produced from refined organic material. It is unique in its ability to produce, dissipate and distribute heat as required.",
		value: 180000,
		ingredients: [
			{
				id: "frost_crystal",
				name: "Frost Crystal",
				quantity: 100
			},
			{
				id: "solanium",
				name: "Solanium",
				quantity: 200
			}
		]
	},
	{
		id: "hermetic_seal",
		name: "Hermetic Seal",
		type: "Crafted Products",
		description: "A high-performance carbon seal, able to withstand both the harsh interstellar environment and the rigours of intensive, high-energy industrial use. User is advised to regularly check seal integrity after installation.",
		value: 800
	},
	{
		id: "herox",
		name: "Herox",
		type: "Crafted Products",
		description: "Herox is a tradeable that can be crafted, found in containers or purchased.",
		value: 25000,
		ingredients: [
			{
				id: "ammonia",
				name: "Ammonia",
				quantity: 50
			},
			{
				id: "ionised_cobalt",
				name: "Ionised Cobalt",
				quantity: 50
			}
		]
	},
	{
		id: "hex_core",
		name: "Hex Core",
		type: "Curiosities",
		description: "This strange energy orb constantly vibrates, emitting a low-frequency drone. Slight variations in the pattern repeat over and over, almost as if it is attempting to relay a message.",
		value: 16
	},
	{
		id: "holographic_analyser",
		name: "Holographic Analyser",
		type: "Crafted Products",
		description: "A temporary frigate upgrade that lasts for one expedition. This powerful analytic computer overclocks the existing fleet systems, allowing for faster-than-light calculations. Heat is a problem, and the chips do not last long.",
		value: 75000
	},
	{
		id: "hot_ice",
		name: "Hot Ice",
		type: "Crafted Products",
		description: "A paradoxical material, made less mysterious by its relative ease of manufacture.",
		value: 400000,
		ingredients: [
			{
				id: "enriched_carbon",
				name: "Enriched Carbon",
				quantity: 1
			}, 
			{
				id: "nitrogen_salt",
				name: "Nitrogen Salt",
				quantity: 1
			}
		]
	},
	{
		id: "hydraulic_wiring",
		name: "Hydraulic Wiring",
		type: "Crafted Products",
		description: "Specialist wiring and control threads, this flexible material allows the transmission of power and signals, as well as offering direct manipulation of remote components. Used in the creation of a wide range of advanced technologies.",
		value: 3600
	},
	{
		id: "hydrothermal_fuel_cell",
		name: "Hydrothermal Fuel Cell",
		type: "Crafted Products",
		description: "A high thermal energy fuel, contained within a standardised fuel cell. Used to fuel the Humboldt Drive that powers the Nautilon submarine. Created with a mix of organic compounds (Carbon and cyto-phosphates) and localised mineral salts.",
		value: 7200
	},
	{
		id: "hypnotic_eye",
		name: "Hypnotic Eye",
		type: "Curiosities",
		description: "The eye is cold, almost frozen, to the touch. Nonetheless, it is impossible to escape the feeling it is somehow still alive. Extended exposure is not recommended. Do not stare back into the eye. Do not stare back. Do not stare back.",
		value: 57000
	},
	{
		id: "indium",
		name: "Indium",
		type: "Raw Materials",
		description: "A chromatic metal, generated by fusion in the heart of a star. Such stellar material ends up forming deposits in the crust of local planets. Indium is found on planets orbiting blue stars, and can be placed in a Refiner to create purified Chromatic Metal for use in the manufacture of advanced technologies.",
		value: 464
	},
	{
		id: "ion_battery",
		name: "Ion Battery",
		type: "Crafted Products",
		description: "Convenient and optimised power storage unit. Used in a wide variety of defensive and hazard protection systems. Constructed by fusing Ferrite Dust with underground Cobalt. Frequently found ready-made in cylindrical metal containers.",
		value: 200
	},
	{
		id: "ionised_cobalt",
		name: "Ionised Cobalt",
		type: "Raw Materials",
		description: "A highly energised form of Cobalt, this processed metal can be used to create Advanced Ion Batteries, a conveniently portable source of energy for the Exosuit. In widespread use as a key component in the creation of advanced technologies and structures.",
		value: 401,
		ingredients: [
			{
				id: "cobalt",
				name: "Cobalt",
				quantity: 2
			}
		]

	},
	{
		id: "iridesite",
		name: "Iridesite",
		type: "Crafted Products",
		description: "Advanced light metal alloy traded throughout the galactic Outer Edge. Often used in the interiors of trading shuttles to reduce weight as they ascend from planets with high gravitational fields.",
		value: 150000,
		ingredients: [
			{
				id: "aronium",
				name: "Aronium",
				quantity: 1
			}, 
			{
				id: "magno_gold",
				name: "Magno Gold",
				quantity: 1
			}, 
			{
				id: "grantine",
				name: "Grantine",
				quantity: 1
			}
		]
	},
	{
		id: "kelp_sac",
		name: "Kelp Sac",
		type: "Raw Materials",
		description: "A rubbery, luminescent sac harvested from underwater Candle Kelp plants. Agricultural science has not yet tamed the Candle Kelp. As such, these sacs cannot be farmed.",
		value: 41
	},
	{
		id: "korvax_casing",
		name: "Korvax Casing",
		type: "Curiosities",
		description: "The metallic shell of a disconnected electronic lifeform that was too distant from its own kind to be refreshed with a new entity. Highly prized by all species, not least its own.",
		value: 22000
	},
	{
		id: "korvax_cube",
		name: "Korvax Cube",
		type: "Curiosities",
		description: "Device used by the Korvax for the storage of historical and cultural information.",
		value: 13063
	},
	{
		id: "larval_core",
		name: "Larval Core",
		type: "Curiosities",
		description: "A pulsating jellied orb, this gooey sphere is warm to the touch. Its stench triggers a primal fear in mortal beings, a deep-seated gnawing that begs you to drop it and flee.",
		value: 69875
	},
	{
		id: "lemmium",
		name: "Lemmium",
		type: "Crafted Products",
		description: "Pure Ferrite alloy. Crafted from Pure Ferrite and Uranium. Used extensively in starship freighter construction due to its sheer strength. A hardcore material popular on the Galactic Trade Network.",
		value: 25000,
		ingredients: [
			{
				id: "uranium",
				name: "Uranium",
				quantity: 50
			}, 
			{
				id: "pure_ferrite",
				name: "Pure Ferrite",
				quantity: 100
			}
		]
	},
	{
		id: "life_support_gel",
		name: "Life Support Gel",
		type: "Crafted Products",
		description: "Emergency life support fuel. Synthesised from rocket fuel crystals and carbon, this gel offers a temporary boost to Life Support systems. Long-term impact on a user's lungs is currently unknown.",
		value: 200
	},
	{
		id: "living_glass",
		name: "Living Glass",
		type: "Crafted Products",
		description: "An advanced building material, this glass has been imbued with organic compounds that allow it to react to the environment. Microbes within the glass filter harmful light of all wavelengths and balance the atmosphere as required.",
		value: 566000,
		ingredients: [
			{
				id: "glass",
				name: "Glass",
				quantity: 5
			}, 
			{
				id: "lubricant",
				name: "Lubricant",
				quantity: 1
			}
		]
	},
	{
		id: "living_pearl",
		name: "Living Pearl",
		type: "Curiosities",
		description: "Born in the hearts of enormous glowing molluscs found deep underwater. Unlike most pearls, this sample is no unliving calcite. Some trace of the mother-clam's consciousness remains within the gem, giving it a lingering, haunting beauty.",
		value: 4797.5
	},	
	{
		id: "living_slime",
		name: "Living Slime",
		type: "Raw Materials",
		description: "A heavy, oozing slime. It is moving gently, as if it has a heartbeat of its own. Nutrient source: unknown.",
		value: 20
	},
	{
		id: "liquid_explosive",
		name: "Liquid Explosive",
		type: "Crafted Products",
		description: "A general purpose high explosive, offered in liquid form for convenience of transport and deployment. Do not drink.",
		value: 800500,
		ingredients: [
			{
				id: "acid",
				name: "Acid",
				quantity: 1
			}, 
			{
				id: "unstable_gel",
				name: "Unstable Gel",
				quantity: 1
			}
		]
	},
	{
		id: "lubricant",
		name: "Lubricant",
		type: "Crafted Products",
		description: "A synthetic lubricant that reduces wear and prolongs the lifespan of technologies with moving parts.",
		value: 110000,
		ingredients: [
			{
				id: "gamma_root",
				name: "Gamma Root",
				quantity: 400
			}, 
			{
				id: "faecium",
				name: "Faecium",
				quantity: 50
			}
		]
	},
	{
		id: "magnetic_resonator",
		name: "Magnetic Resonator",
		type: "Crafted Products",
		description: "An electromagnetic frequency oscillator, able to function in a wide-range of conditions thanks to both ferrous and non-ferrous magnetic properties. Used in the creation of a wide range of advanced technologies.",
		value: 6150
	},
	{
		id: "magnetised_ferrite",
		name: "Magnetised Ferrite",
		type: "Raw Materials",
		description: "Highly processed metal, requiring several stages of processing in a Refiner. Used in the creation of advanced structures and technologies. Avoid ingestion.",
		value: 82
	},
	{
		id: "magno_gold",
		name: "Magno-Gold",
		type: "Crafted Products",
		description: "Highly prized and lustrous alloy. Popular with traders of all known primary galactic races. Crafted from Ionised Cobalt and Phosphorus. Easily recognisable by its bright red glow and strong magnetic field.",
		value: 25000,
		ingredients: [
			{
				id: "phosphorus",
				name: "Phosphorus",
				quantity: 50
			}, 
			{
				id: "ionised_cobalt",
				name: "Ionised Cobalt",
				quantity: 50
			}
		]
	},
	{
		id: "marrow_bulb",
		name: "Marrow Bulb",
		type: "Raw Materials",
		description: "A glowing organic bulb, harvested from the Cave Marrow plant found growing underground. The Cave Marrow has proved resistant to domestication, and no farmable cultivars are known to exist. As such, marrow bulbs must be harvested by hand in the wild.",
		value: 41
	},
	{
		id: "metal_plating",
		name: "Metal Plating",
		type: "Crafted Products",
		description: "A lightweight metal product, heavily used in the manufacture of starship parts and deployable technology. A mainstay of the construction industries of all known primary species.	Crafted from Ferrite Dust.",
		value: 800
	},
	{
		id: "microprocessor",
		name: "Microprocessor",
		type: "Crafted Products",
		description: "A compact, low-heat microchip. Assembled from processed Chromatic Metal, created from one of several specialised terrain metals. Used in the creation of a wide range of advanced technologies.",
		value: 2000
	},
	{
		id: "mind_arc",
		name: "Mind Arc",
		type: "Curiosities",
		description: "A strange piece of technology, a gift from beyond the stars. It shimmers in a way that suggests it is not fully in this world.",
		value: 1000
	},
	{
		id: "mind_control_device",
		name: "Mind Control Device",
		type: "Crafted Products",
		description: "A temporary frigate upgrade that lasts for one expedition. The mind control device plugs into the ship's trading and communications systems, allowing the Fleet Commander to gain the upper hand in any negotiation.",
		value: 75000
	},
	{
		id: "mineral_compressor",
		name: "Mineral Compressor",
		type: "Crafted Products",
		description: "A temporary frigate upgrade that lasts for one expedition. The mineral compressor allows fleet mining crews to liquidise the substances they extract, for both faster processing and easier transportation.",
		value: 75000
	},
	{
		id: "modified_quanta",
		name: "Modified Quanta",
		type: "Curiosities",
		description: "This one-of-a-kind Atlas Seed holds an aesthetically pleasing mathematical construct salvaged from the simulation of an alternate reality.",
		value: 1000
	},
	{
		id: "mordite",
		name: "Mordite",
		type: "Raw Materials",
		description: "Despite much study, little is known about this haunting, crystalline compound. It is released from the cadavers of dying creatures, but can also be specifically cultivated and harvested from the Mordite Root plant.",
		value: 40
	},
	{
		id: "mordite_root",
		name: "Mordite Root",
		type: "Crafted Products",
		description: "An inedible tuber that produces a small yield of Mordite crystals. A peaceful alternative to the process of harvesting Mordite from the corpses of creatures. Mordite Root must be grown in a Hydroponics Tray. Approximate growing time: 8 hours",
		value: 3
	},
	{
		id: "nipnip",
		name: "NipNip",
		type: "Crafted Products",
		description: "This medicinal herb is known for its pungent buds, which are harvested to produce Gek Nip. NipNip thrives in dank environments, and often grows as a weed. Suitable for hydroponic planting indoors. Needs a tropical or humid climate before planting outdoors.",
		value: 3
	},
	{
		id: "nipnip_buds",
		name: "NipNip Buds",
		type: "Curiosities",
		description: "A pungent bud harvested from the NipNip plant, often used to produce GekNip.",
		value: 17776
	},
	{
		id: "nitrogen", 
		name: "Nitrogen",
		type: "Raw Materials",
		description: "A reactive atmospheric gas found wherever there is organic life. Nitrogen is readily harvested from the atmospheres of Lush and Toxic planets.",
		value: 20
	},
	{
		id: "nitrogen_salt",
		name: "Nitrogen Salt",
		type: "Crafted Products",
		description: "A refined product, this is a powerful organic fertiliser in an easily distributed form.",
		value: 50000,
		ingredients: [
			{
				id: "nitrogen",
				name: "Nitrogen",
				quantity: 250
			}, 
			{
				id: "condensed_carbon",
				name: "Condensed Carbon",
				quantity: 50
			}
		]
	},
	{
		id: "noospheric_orb",
		name: "Noospheric Orb",
		type: "Curiosities",
		description: "An Atlas Seed capable of resonating on humanoid telepathic frequencies; may attempt to subsume any subordinate intellect in close proximity.",
		value: 1000
	},
	{
		id: "novae_reclaiment",
		name: "Novae Reclaiment",
		type: "Curiosities",
		description: "Atlas Seed contains neutronium elements from a catastrophic supernova event that obliterated a sentient civilization in an earlier era.",
		value: 1000
	},
	{
		id: "organic_catalyst",
		name: "Organic Catalyst",
		type: "Crafted Products",
		description: "A catalytic material used in the creation of many organic fertilizers.",
		value: 320000,
		ingredients: [
			{
				id: "thermic_condensate",
				name: "Thermic Condensate",
				quantity: 1
			}, 
			{
				id: "enriched_carbon",
				name: "Enriched Carbon",
				quantity: 1
			}
		]
	},
	{
		id: "oxygen",
		name: "Oxygen",
		type: "Raw Materials",
		description: "Integral to the atmospheric filtering technology at the heart of the exosuit life support system.	Exosuit material processing allows oxygen to be harvested directly from appropriate planetary flora. Other plantlife may be scanned with the Analysis Visor to reveal alternative oxygen supplies.",
		value: 34
	},
	{
		id: "paraffinium",
		name: "Paraffinium",
		type: "Raw Materials",
		description: "Local mineral extract, typically found in large deposits or extracted from common materials after inspection with an Analysis Visor. Typically found on planets with a tropical environment.",
		value: 62
	},
	{
		id: "phosphorus",
		name: "Phosphorus",
		type: "Raw Materials",
		description: "Local mineral extract, typically found in large deposits or extracted from common minerals after inspection with an Analysis Visor. Typically found on planets with a scorched environment.",
		value: 62
	},
	{
		id: "photic_jade",
		name: "Photic Jade",
		type: "Curiosities",
		description: "This irreplaceable Atlas Seed is a form of matter-adapted photons coalesced into physical solidity by unknown means.",
		value: 1000
	},
	{
		id: "platinum",
		name: "Platinum",
		type: "Raw Materials",
		description: "Extremely valuable interstellar trading mineral, typically mined from asteroids. Occasionally found in underground planetary deposits. Universally prized for its hardiness and versatility.",
		value: 505
	},
	{
		id: "poly_fibre", 
		name: "Poly Fibre",
		type: "Advanced Agricultural Product",
		description: "A connective fibre for electronics, made from an advanced synthetic polymer and capable of serving as a conduit for power and data.",
		value: 130000,
		ingredients: [
			{
				id: "cactus_flesh",
				name: "Cactus Flesh",
				quantity: 100
			},
			{
				id: "star_bulb",
				name: "Star Bulb",
				quantity: 200
			}
		]
	},
	{
		id: "portable_reactor",
		name: "Portable Reactor",
		type: "Crafted Products",
		description: "A miniature self-controlled nuclear reactor. Generates sub-stellar levels of energy in a hassle-free, widely compatible fuel module.",
		value: 4200000,
		ingredients: [
			{
				id: "liquid_explosive",
				name: "Liquid Explosive",
				quantity: 1
			}, 
			{
				id: "fusion_accelerant",
				name: "Fusion Accelerant",
				quantity: 1
			}
		]
	},
	{
		id: "projectile_ammunition",
		name: "Projectile Ammunition",
		type: "Crafted Products",
		description: "Advanced munition fragments, constructed to fit Universal Multi-Tool Standard 07/FF1. Easily inserted into the Boltcaster, Pulse Spitter and Scatter Blaster via the Multi-Tool clip reloading system.",
		value: 1
	},
	{
		id: "pugneum",
		name: "Pugneum",
		type: "Raw Materials",
		description: "This oily, unsettling liquid leaks from the circuitry of Sentinels. Prized by the Vy'keen, Pugneum is thought to share some essential properties with Nanites. It hums in a sinister fashion upon contact with organic matter.",
		value: 138
	},
	{
		id: "pure_ferrite",
		name: "Pure Ferrite",
		type: "Raw Materials",
		description: "Processed metal, free of dust and pebbles. Used to construct a wide variety of structures and technologies. Typically purified from Ferrite dust using a Refiner, but can occasionally be found in large deposits. Collection may require an Advanced Mining Laser.",
		value: 138
	},
	{
		id: "pyrite",
		name: "Pyrite",
		type: "Raw Materials",
		description: "Local mineral extract, typically found in large deposits or extracted from common materials after inspection with an Analysis Visor. Typically found on planets with a desert environment.",
		value: 62
	},
	{
		id: "quad_servo",
		name: "Quad Servo",
		type: "Curiosities",
		description: "A highly sprung motor arm salvaged from inside of a Sentinel patrol unit. It occasionally twitches, as if experiencing the echo of combat.",
		value: 20000
	},
	{
		id: "quantum_computer",
		name: "Quantum Computer",
		type: "Crafted Products",
		description: "An extremely fast advanced processing unit. Allows real-time solving of otherwise impossible calculations. However, protection against decoherence is not guaranteed. Used in the creation of a wide range of advanced technologies.",
		value: 4200
	},
	{
		id: "quantum_processor",
		name: "Quantum Processor",
		type: "Crafted Products",
		description: "A highly advanced computational device, essential for the complex calculations involved in warp travel.",
		value: 5200000,
		ingredients: [
			{
				id: "circuit_board",
				name: "Circuit Board",
				quantity: 1
			}, 
			{
				id: "superconductor",
				name: "Superconductor",
				quantity: 1
			}
		]
	},
	{
		id: "radon",
		name: "Radon",
		type: "Raw Materials",
		description: "A colourless, odourless gas with a relatively short half-life. Found in both Radioactive and Frozen atmospheres, this gas is produced by the decay of other high-energy elements.",
		value: 20
	},
	{
		id: "residual_goop",
		name: "Residual Goop",
		type: "Raw Materials",
		description: "A pulsating, foul smelling goop that builds up in poorly-maintained machinery. Skin contact is not advised.",
		value: 20
	},
	{
		id: "runaway_mould",
		name: "Runaway Mould",
		type: "Raw Materials",
		description: "An out of control mould growth that builds up in poorly-maintained machinery. Likely to be several different species of mould, merged together into one super-colony.",
		value: 20
	},
	{
		id: "rusted_metal",
		name: "Rusted Metal",
		type: "Raw Materials",
		description: "Handfulls of corroded metal, distorted by years of exposure to the harsh environment. Handle with care.",
		value: 20
	},
	{
		id: "sac_venom",
		name: "Sac Venom",
		type: "Curiosities",
		description: "Stabilized poison sample initially produced by aquatic urchin creatures. A rare and expensive item on the Galactic Trade Network.",
		value: 608000
	},
	{
		id: "salt",
		name: "Salt",
		type: "Raw Materials",
		description: "A naturally occuring salt, found in abundance in underwater minerals. Can be processed in a Refiner to create Chlorine. This refined form is used in the manufacture of advanced products and technologies.",
		value: 299
	},
	{
		id: "silicate_powder",
		name: "Silicate Powder",
		type: "Raw Materials",
		description: "An abundant mineral element, found within the geological strata of all rocky worlds. Easily extracted using a Terrain Manipulator. Create a tunnel anywhere to begin extraction. Process in a Refiner to create Glass.",
		value: 2
	},
	{
		id: "silver",
		name: "Silver",
		type: "Raw Materials",
		description: "Valuable interstellar trading mineral, typically mined from asteroids. Occasionally found in underground planetary deposits. Prized by people in all systems for its lustre and shine.",
		value: 186
	},
	{
		id: "semiconductor",
		name: "Semiconductor",
		type: "Crafted Products",
		description: "An advanced material useful in many electronic devices, with its own in-built temperature regulator. Crafted from Thermic Condensate and Nitrogen Salt.",
		value: 15600000,
		ingredients: [
			{
				id: "thermic_condensate",
				name: "Thermic Condensate",
				quantity: 1 
			},
			{
				id: "nitrogen_salt",
				name: "Nitrogen Salt",
				quantity: 1
			}
		]
	},
	{
		id: "sodium",
		name: "Sodium",
		type: "Raw Materials",
		description: "A powerful catalyst, useful for charging defensive technologies such as shields or hazard protection. Exosuit material handling technology allows automatic harvesting from appropriate sodium-rich flora. A vital ingredient in the creation of many advanced devices, products and components.",
		value: 41
	},
	{
		id: "sodium_nitrate",
		name: "Sodium Nitrate",
		type: "Raw Materials",
		description: "An advanced catalyst, useful for charging defensive technologies such as shields or hazard protection. Created in a Refiner, or occasionally found in crystalline form on a planet's surface. Offers a substantially improved energy-per-gram ratio over regular Sodium.",
		value: 82
	},
	{
		id: "solanium",
		name: "Solanium",
		type: "Raw Materials",
		description: "A powerful chemical that has resisted attempts at synthesis. It can be harvested from the bark of the Solar Vine. The vine requires a hot climate to thrive in the wild, but can be farmed in all environments with the aid of a Hydroponics Tray.",
		value: 70
	},
	{
		id: "solar_mirror",
		name: "Solar Mirror",
		type: "Crafted Products",
		description: "A specialist optical component. Employing an impossibly polished surface, this mirror is able to selectively filter different wavelengths of light, changing its reflective pattern based on nearby magnetic fields. Used in the creation of a wide range of advanced technologies.",
		value: 6150
	},
	{
		id: "solar_vine",
		name: "Solar Vine",
		type: "Crafted Products",
		description: "This 'living rock' is adapted to live in the extreme heat of scorched biomes. However, it can be farmed in most environments and, once established, yields a moderate harvest. Suitable for hydroponic indoor planting. Ensure Hot climate before planting outdoors. Approximate growing time: 16 hours",
		value: 3
	},
	{
		id: "star_bramble",
		name: "Star Bramble",
		type: "Crafted Products",
		description: "A medium-sized, farmable plant that yields an occasional harvest of valuable Star Bulbs. Suitable for hydroponic indoor planting. Ensure Lush climate before planting outdoors. Approximate growing time: 4 hours",
		value: 3
	},
	{
		id: "star_bulb",
		name: "Star Bulb",
		type: "Raw Materials",
		description: "A beautiful gemstone, this prized product is the engorged, luminescent berry of the Star Bramble. The host plant requires lush conditions to thrive in the wild but can be farmed in all environments with the aid of a Hydroponic Tray.",
		value: 32
	},
	{
		id: "stasis_device",
		name: "Stasis Device",
		type: "Crafted Products",
		description: "A device specifically crafted to keep lifeforms alive for thousands of years longer than their natural lifespan. Such a device requires great skill to manufacture, as not only is it technically complex, but the consequences for a user in the event of malfunction would be disastrous.",
		value: 15600000,
		ingredients: [
			{
				id: "quantum_processor",
				name: "Quantum Processor",
				quantity: 1 
			},
			{
				id: "cryogenic_chamber",
				name: "Cryogenic Chamber",
				quantity: 1
			},
			{
				id: "iridesite",
				name: "Iridesite",
				quantity: 1 
			}
		]
	},
	{
		id: "state_phasure",
		name: "State Phasure",
		type: "Curiosities",
		description: "For unknown reasons, this unique Atlas Seed has been phased out of alignment with this quantum reality. Contents cannot be determined.",
		value: 1000
	},
	{
		id: "sulphurine", 
		name: "Sulphurine",
		type: "Raw Materials",
		description: "A pungent atmospheric gas. High concentrations are extremely hazardous to organic life. With the aid of specialised machinery, can be extracted from the atmospheres of Scorched and Desert planets.",
		value: 20
	},
	{
		id: "superconductor",
		name: "Superconductor",
		type: "Crafted Products",
		description: "An advanced conductive material, the superconductor further enriches the field-warping power of the Semiconductor.",
		value: 2000000,
		ingredients: [
			{
				id: "enriched_carbon",
				name: "Enriched Carbon",
				quantity: 1
			},
			{
				id: "semiconductor",
				name: "Semiconductor",
				quantity: 1
			}
		]
	},
	{
		id: "tainted_metal",
		name: "Tainted Metal",
		type: "Raw Materials",
		description: "Shredded fragments of a soft, grey metal. Its surface is porous, and when touched it oozes ever-so-slightly. Found in the creaking wreck of a derelict freighter. The space station Scrap Dealer may find this interesting...",
		value: 380
	},
	{
		id: "thermic_condensate",
		name: "Thermic Condensate",
		type: "Crafted Products",
		description: "A refined product, holding the energy potential of heated atmospheric gas in a stable state until required.",
		value: 50000,
		ingredients: [
			{
				id: "sulphurine",
				name: "Sulphurine",
				quantity: 250
			}, 
			{
				id: "condensed_carbon",
				name: "Condensed Carbon",
				quantity: 50
			}
		]
	},
	{
		id: "tritium",
		name: "Tritium",
		type: "Raw Materials",
		description: "Radioactive isotope commonly used to fuel the fusion reactor at the heart of starship Pulse Engines. Abundant in interstellar asteroid fields, Tritium can be mined from asteroids using starship weaponry.",
		value: 6
	},
	{
		id: "unstable_gel",
		name: "Unstable Gel",
		type: "Crafted Products",
		description: "A highly reactive gel, this substance is both energy-rich and dangerous to touch.",
		value: 50000,
		ingredients: [
			{
				id: "cactus_flesh",
				name: "Cactus Flesh",
				quantity: 200
			}
		]
	},
	{
		id: "unstable_plasma",
		name: "Unstable Plasma",
		type: "Crafted Products",
		description: "Densely-packed fuel capsule for use in the Plasma Launcher. Contained highly-pressurised electro-thermal energy for use in land disruption grenade technology.",
		value: 5750
	},
	{
		id: "uranium",
		name: "Uranium",
		type: "Raw Materials",
		description: "Local mineral extract, typically found in large deposits or extracted from common minerals after inspection with an Analysis Visor. Typically found on planets with a radioactive environment.",
		value: 62
	},
	{
		id: "venom_urchin",
		name: "Venom Urchin",
		type: "Crafted Products",
		description: "A small, innocuous looking plant whose leaves periodically secrete a small amount of potent Sac Venom, a valuable trading commodity. Suitable for hydroponic indoor planting. Cannot be planted outdoors. Approximate growing time: 3 hours 20 mins",
		value: 3
	},
	{
		id: "viscous_fluids",
		name: "Viscous Fluids",
		type: "Raw Materials",
		description: "An unnaturally thick liquid of dubious colour. Its origins are impossible to fathom. Appears to have some mild magnetic properties.",
		value: 20
	},
	{
		id: "void_egg",
		name: "Void Egg",
		type: "Curiosities",
		description: "An anomalous egg. The shell is tough and leathery, and twitches when touched. A faint tapping can be heard within. From time to time, it appears to sing.",
		value: 3200
	},
	{
		id: "vortex_cube",
		name: "Vortex Cube",
		type: "Curiosities",
		description: "An ancient object, unearthed from the depths of a planetary cave system. Its surface is cold to the touch, and is curiously polished despite its age. A fusion of metal and rock, these cubes have proved resistant to industrial processing. As such, they are of value only to collectors. Can be sold at a Galactic Trade Terminal.",
		value: 5800
	},
	{
		id: "vykeen_dagger",
		name: "Vy'keen Dagger",
		type: "Curiosities",
		description: "Largely ceremonial weapon. A vital part of Vy'keen tradition and culture.",
		value: 11688
	},
	{
		id: "vykeen_effigy",
		name: "Vy'keen Effigy",
		type: "Curiosities",
		description: "A small wooden icon carved into the shape of a Sentinel drone. Used by warriors to enter a temporary trance-like state that eliminates their kind's need for sleep.",
		value: 24750
	},
	{
		id: "vykeen_tablet",
		name: "Vy'keen Tablet",
		type: "Curiosities",
		description: "A stone tablet bearing line after line of intricate runes. The words are unintelligible, an ancient dialect forgotten by all but the oldest of the Vy'keen elders. The hand that carved this stone must have been extraordinary. The stonework is precise, delicate - and yet perfectly conveys the unyielding aggression its writer clearly possessed.",
		value: 1250
	},
	{
		id: "walker_brain",
		name: "Walker Brain",
		type: "Curiosities",
		description: "Shifting nanite clusters sewn together with a pugneum filament, this circuit is painfully hot to the touch. A sinister purple light leaks from deep within its wiring, changing in intensity as it watches its holder.",
		value: 35000
	},
	{
		id: "warp_cell",
		name: "Warp Cell",
		type: "Crafted Products",
		description: "This antimatter-based fuel is one of the few power sources capable of meeting the incredible energy requirements of a starship hyperdrive. Secured within a robust housing, the cell is guaranteed paradox-free during FTL travel.",
		value: 46750
	},
	{
		id: "warp_hypercore",
		name: "Warp Hypercore",
		type: "Crafted Products",
		description: "A high-capacity antimatter-based fuel, this cell harnesses an internal black hole generator to power starship hyperdrives across multiple warp jumps. Cell walls are specially designed to reflect any reality paradoxes back towards the heart of the unit, where they generate additional power.",
		value: 46750
	},
	{
		id: "wiring_loom",
		name: "Wiring Loom",
		type: "Crafted Products",
		description: "A prefabricated circuit board, designed for flexible use in a large range of technology components. The module features an integrated nanite processor, allowing it to be quickly configured for a wide variety of uses.",
		value: 25000
	}
];

// todo: add missing item data (ONGOING)
// todo: alphabetize existing data (ONGOING)
// todo: add missing crafting data
// todo: fill in missing color data for new resources (?) this might not be needed since the new update is more minimalist
// todo: refactor css item ids into classes (?) again this might not be necessary from a design standpoint, review new game UI
// todo: get pathing working, and push in-app navigation events to browser history
// todo: fix mobile menu (hide all but "all items," make dropdown more mobile friendly)
// todo: remove width from .stats (?) and .details;  move to .column's (in form of x% of .container, and .container has varying width per breakpoint),

var app = new Vue({
    el: "#app",
    data: {
		items: items,
		selected_item: "stasis_device",
		filter: ""
    },
    methods: {
		load_item: function(item_id){
			this.selected_item = item_id;
		},
		toggleDrawer: function(drawerId){
			// Close any other open drawers
			var allDrawers = document.getElementsByClassName("drawer");
			for(var i = 0; i < allDrawers.length; i++){
				if(allDrawers[i].parentNode.id != drawerId){
					allDrawers[i].parentNode.classList.remove("open");
				}
			}
			// Toggle this drawer
			var thisDrawer = document.querySelector(`#${drawerId} .drawer`);
			thisDrawer.parentNode.classList.toggle("open");
		}
    },
	computed: {
		item_selected(){
			return this.items.filter(item => {
				return item.id === this.selected_item;
			})
		},
		items_filtered(){
			return this.items.filter(item => {
				return item.name.toLowerCase().indexOf(this.filter.toLowerCase()) > -1;
			})
		},
		items_raw_materials(){
			return this.items.filter(item => {
				return item.type === "Raw Materials";
			})
		},
		items_crafted_products(){
			return this.items.filter(item => {
				return item.type === "Crafted Products";
			})
		},
		items_curiosities(){
			return this.items.filter(item => {
				return item.type === "Curiosities";
			})
		}
	},
	beforeMount(){},
	mounted(){},
	updated(){}
})

// Vanilla-Tilt
VanillaTilt.init(document.querySelector(".card"), {
	max: 16,
	speed: 400,
	glare: true,
	"max-glare": 0.75,
	reverse: true
});